version: "3"

services:
  publisher:
    build: ./publisher
    network_mode: "host"
    tty: true
    environment:
      - RABBITMQ_HOST
      - RABBITMQ_USER
      - RABBITMQ_PASSWORD
      - RABBITMQ_QUEUE
      - RABBITMQ_DURABLE
      - RABBITMQ_DELIVERY_MODE
